PLUGIN_NAME=		checkmk-agent-mini
PLUGIN_VERSION=		0.1
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Checkmk monitoring agent (minimal package)
PLUGIN_MAINTAINER=	robin.gierse@checkmk.com
PLUGIN_DEPENDS=		bash libstatgrab

.include "../../Mk/plugins.mk"
